
var nameList = [
  "Aarav",
  "Vivaan",
  "Aditya",
  "Krishna",
  "Aryan",
  "Rohan",
  "Kartik",
  "Lakshya",
  "Rudra",
  "Shivansh",
  "Anaya",
  "Diya",
  "Ishita",
  "Kavya",
  "Saanvi",
  "Myra",
  "Avni",
  "Tanya",
  "Meera",
  "Nitya",
  "Riya",
  "Priya",
  "Aarohi",
  "Trisha",
  "Yash",
  "Manav",
  "Veer",
  "Devansh",
  "Kabir",
  "Arjun",
  "Anika",
  "Reyansh",
  "Tanvi",
  "Ira",
  "Shaurya",
  "Advait",
  "Om",
  "Naman",
  "Vihaan",
  "Harsh",
  "Harshita",
  "Sneha",
  "Pooja",
  "Sakshi",
  "Neha",
  "Tushar",
  "Gaurav",
  "Nikhil",
  "Siddharth",
  "Rachit",
  "Utkarsh",
  "Raj",
  "Rahul",
  "Abhishek",
  "Karan",
  "Amit",
  "Anjali",
  "Bhavya",
  "Shruti",
  "Madhav",
  "Parth",
  "Ishan",
  "Dhruv",
  "Pranav",
  "Ayush",
  "Aayushi",
  "Nivedita",
  "Ritu",
  "Divya",
  "Smriti",
  "Komal",
  "Chirag",
  "Saurabh",
  "Sandeep",
  "Varun",
  "Ritika",
  "Nikhita",
  "Rajeev",
  "Kishan",
  "Bhavesh",
  "Sonal",
  "Siddhi",
  "Kshitij",
  "Deepak",
  "Ravi",
  "Ajay",
  "Vikas",
  "Alok",
  "Payal",
  "Swati",
  "Jaya",
  "Radha",
  "Manisha",
  "Arpita",
  "Jyoti",
  "Sudhir",
  "Sunil",
  "Ashok",
  "Sameer",
  "Pankaj",
  "Rekha",
  "Seema",
  "Tanmay",
  "Sharv",
  "Indira",
  "Lakshmi",
  "Sita",
  "Kiran",
  "Preeti",
  "Mansi",
  "Hemant",
  "Lalit",
  "Ramesh",
  "Suresh",
  "Kamal",
  "Rajesh",
  "Suman",
  "Hemlata",
  "Geeta",
  "Bharti",
  "Harshit",
  "Tanu",
  "Ashwini",
  "Asha",
  "Namrata",
  "Mithun",
  "Mahesh",
  "Ankita",
  "Deepa",
  "Vidya",
  "Prachi",
  "Nilesh",
  "Yuvraj",
  "Shreya",
  "Palak",
  "Rupal",
  "Amrita",
  "Anup",
  "Ragini",
  "Vibha",
  "Devika",
];


export function generateRandomName() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}


export function makeRandomMessage() {
  const comments = [
    "🔥🔥🔥",
    "This is lit!",
    "Who's watching in 2025?",
    "Love from India 🇮🇳",
    "Underrated channel 💯",
    "He deserves more views!",
    "I'm early!",
    "Can’t stop watching this 😂",
    "Anyone else vibing?",
    "This is better than Netflix!",
    "Drop a like if you're enjoying!",
    "This song on repeat 🔁",
    "Bro is on fire 🔥",
    "Comment section never disappoints 😂",
    "Waiting for this to blow up 🚀",
    "Big fan from Kolkata!",
    "What a banger! 💥",
    "OMG the beat drop 😍",
    "Respect to the creator 🙏",
    "Here before 1M views!",
    "Just discovered this gem 💎",
    "Who else got goosebumps? 🥶",
    "LEGENDARY stuff 👑",
    "This deserves an award 🏆",
    "Even my mom liked this lol 😆",
    "Why isn’t this viral yet?",
    "Song of the year! 🏅",
    "Love this community ❤️",
    "Never disappoints 💯",
    "That transition tho 👌",
    "Chills. Just chills.",
    "Vibe check ✅",
    "Back again like always!",
    "This should have more likes!",
    "So wholesome 😊",
    "Who came here from TikTok?",
    "Bruh 🔥🔥🔥",
    "Replay button is broken 🔁",
    "Pure talent 🙌",
    "Still better than 99% of the industry!",
  ];

  const randomIndex = Math.floor(Math.random() * comments.length);
  return comments[randomIndex];
}
